# Generated by npins
let
  data = builtins.fromJSON (builtins.readFile ./sources.json);
  version = data.version;

  mkSource = name: spec:
    if spec.type == "Git" then
      builtins.fetchGit ({
        url = spec.url;
        rev = spec.revision;
      } // (if spec ? submodules then { inherit (spec) submodules; } else {}))
    else if spec.type == "Channel" then
      builtins.fetchTarball ({
        url = "https://channels.nixos.org/${spec.name}/nixexprs.tar.xz";
      } // (if spec ? hash then { sha256 = spec.hash; } else {}))
    else if spec.type == "GitHub" then
      builtins.fetchTarball ({
        url = "https://github.com/${spec.owner}/${spec.repo}/archive/${spec.revision}.tar.gz";
      } // (if spec ? hash then { sha256 = spec.hash; } else {}))
    else
      throw "unsupported source type ${spec.type}";
in
  if version != 3 then
    throw "unsupported sources.json version ${toString version}"
  else
    builtins.mapAttrs mkSource data.pins
